language: node
node:
- '10.13'
services:
  postgresql
sudo: false
dist: trusty
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
env:
  global:
  - JOBS=1
before_install:
- openssl aes-256-cbc -K $encrypted_a26860948143_key -iv $encrypted_a26860948143_iv
  -in deploy_key.enc -out deploy_key -d
- npm config set spin false
install:
- npm ci --prefix ./api
- npm ci --prefix ./app
- knex migrate:latest --knexfile ./app/knexfile.js
script:
- node api/index.js >> /dev/null &
- npm run lint:js --prefix ./app
- npm start --prefix ./app >> /dev/null &
- npm run cypress:run --prefix ./app
- kill $(jobs -p) || true
deploy:
  - providor: script
    script: GIT_SSH_COMMAND="ssh -i ./deploy_key" git push $DEPLOY_REPO
    on:
      branch: master
  - providor: script
    script: GIT_SSH_COMMAND="ssh -i ./deploy_key" git push $DEPLOY_REPO
    on:
      branch: production