# Generated by Django 2.0.5 on 2018-06-24 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managetime', '0020_auto_20180529_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='birthdate',
            field=models.DateField(blank=True, db_column='birthdate', null=True),
        ),
        migrations.RenameField('circle','birthdate', 'birth_date'),
        
        migrations.AlterField(
            model_name='circle',
            name='supercircle',
            field=models.ForeignKey(blank=True, db_column='supercircle', null=True, on_delete=django.db.models.deletion.PROTECT, to='managetime.Circle'),
        ),
        migrations.RenameField('circle','supercircle', 'super_circle'),
        
        migrations.AlterField(
            model_name='kummitment',
            name='dayscheduled',
            field=models.DateField(blank=True, db_column='dayscheduled', help_text='Do you want to schedule this kummitment for a specific day? If so, which one?', null=True, verbose_name='Date scheduled'),
        ),
        migrations.RenameField('kummitment','dayscheduled', 'day_scheduled'),
        
        migrations.AlterField(
            model_name='kummitment',
            name='energytype',
            field=models.TextField(blank=True, db_column='energy_type', help_text="Do you want to wait until you have a certain type of energy to energize this kummitment? For example, I (Jay) like to do difficult and creative things when my energy is high, but check emails throughout the day when my energy is low. It's important to learn to monitor (and control) your energy throughout the day -- inability to do this is why many aspiring professionals can't handle freelancing or entrepreneurship (they need to be told what to do or threatened with being punished/fired in order to be productive).", max_length=60, null=True, verbose_name='Energy type'),
        ),
        migrations.RenameField('kummitment','energytype', 'energy_type'),
        
        migrations.AlterField(
            model_name='kummitment',
            name='minutesestimate',
            field=models.DurationField(blank=True, db_column='minutesestimate', help_text="How many minutes do you estimate it will take to complete this kummitment and generate the 'evidence of done'?", null=True, verbose_name='Minute estimate'),
        ),
        migrations.RenameField('kummitment','minutesestimate', 'minutes_estimate'),
        
        migrations.AlterField(
            model_name='kummitment',
            name='nextaction',
            field=models.TextField(db_column='nextaction', help_text="What small thing will need to be done next to start moving toward success? For example, 'open the draft image file in Inkskape', 'find a time to meet with Jay', or 'load the project code into Atom and run the server in Terminal'.", max_length=600, verbose_name='Next action'),
        ),
        migrations.RenameField('kummitment','nextaction', 'next_action'),
        
        migrations.AlterField(
            model_name='kummitment',
            name='possibleobstacles',
            field=models.TextField(db_column='possibleobstacles', help_text="What might stand in the way of accomplishing this kummitment before the deadline? Perhaps it will prove too difficult for you and you won't be able to get the help? Perhaps the task or kummitment is too vague? Maybe you'll get distracted by social media? Write down some ideas and ensure you do all you can to minimize their chances of blocking you.", max_length=600, verbose_name='Possible obstacles'),
            
        ),
        migrations.RenameField('kummitment','possibleobstacles', 'possible_obstacles'),
        
        migrations.AlterField(
            model_name='kummitment',
            name='successactions',
            field=models.TextField(db_column='successactions', help_text="What actions will the kummitor take to accomplish this task and generate the 'evidence of done'?", max_length=600, verbose_name='Success actions'),
            
        ),
        migrations.RenameField('kummitment','successactions', 'success_actions'),
        
        migrations.AlterField(
            model_name='kummitment',
            name='timescheduled',
            field=models.TimeField(blank=True, db_column='timescheduled', help_text='Do you want to schedule this kummitment for a specific time? If so, when?', null=True, verbose_name='Time scheduled'),
        ),
        migrations.RenameField('kummitment','timescheduled', 'time_scheduled'),
        
        migrations.AlterField(
            model_name='kummitment',
            name='weekscheduled',
            field=models.TextField(blank=True, db_column='weekscheduled', help_text='Do you want to schedule this kummitment for a specific week? If so, which one?', max_length=60, null=True, verbose_name='Week scheduled'),
        ),
        migrations.RenameField('kummitment','weekscheduled', 'week_scheduled'),
        
        
        migrations.AlterField(
            model_name='project',
            name='keyresults',
            field=models.TextField(db_column='keyresults', max_length=600),
        ),
        migrations.RenameField('project','keyresults', 'key_results'),
        
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateTimeField(db_column='startdate', default=1),
            
        ),
        migrations.RenameField('project','startdate', 'start_date'),
        
        migrations.AlterField(
            model_name='project',
            name='weeklyreport',
            field=models.TextField(db_column='weeklyreport', max_length=600),
            
        ),
        migrations.RenameField('project','weeklyreport', 'weekly_report'),
        
        
        migrations.AlterField(
            model_name='rolekummitment',
            name='nextaction',
            field=models.TextField(db_column='nextaction', max_length=600),
        ),
        migrations.RenameField('rolekummitment','nextaction', 'next_action'),
        
        migrations.AlterField(
            model_name='task',
            name='startdate',
            field=models.DateTimeField(db_column='startdate', default=django.utils.timezone.now, help_text='When could work begin?', verbose_name='Startline'),
        ),
        migrations.RenameField('task','startdate', 'start_date'),        
    ]
