# Generated by Django 2.0.5 on 2018-06-24 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managetime', '0022_auto_20180624_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kummitment',
            name='problemneedinghelp',
            field=models.TextField(blank=True, db_column='problemneedinghelp', help_text="UNDER CONSTRUCTION. Do you need help with this? Let people know as soon as possible. This will notify any Members or volunteers who have skills in this area so they can help you figure out it. Be sure to define what kind of help you need, and what you've tried before.", max_length=600, null=True, verbose_name='What problem needs help?'),
        ),
        migrations.RenameField('kummitment','problemneedinghelp', 'problem_needing_help'),
      
        migrations.AddField(
            model_name='project',
            name='gig_doing',
            field=models.CharField(null=True, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='gig_finding',
            field=models.CharField(null=True, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='gig_management',
            field=models.CharField(null=True, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='gig_value',
            field=models.CharField(null=True, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='gig_value_details',
            field=models.CharField(db_column='gigvaluedetails', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leading_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='related_roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='managetime.Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.TextField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='achievable',
            field=models.BooleanField(default=False, help_text='With a reasonable amount of effort and application can this be achieved in the deadline by the kummitor? Ideally, goals should be challenging but doable. Do you (or does the kummitor) have the appropriate knowledge, skills, and available energy to get this done on time? You can achieve incredible goals when you plan your steps with clarity and execute those steps with commitment. As you carry out the steps, you can achieve goals that may have initially seemed impossible. On the other hand, if a goal is impossible to achieve, you may not even try to accomplish it. Achievable but slightly challenging goals motivate us, impossible goals demotivate us.'),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='connected',
            field=models.TextField(help_text='(Required) How will energizing this kummitment make you more connected to Tunapanda, your community, and/or the world?', max_length=600),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='When are you kummiting to have this done by? It needs to be before the Task deadline.', null=True),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='healthy',
            field=models.TextField(blank=True, help_text='(Optional) How will energizing this kummitment contribute to your physical, psychological, emotional, and/or spiritual health?', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='kummitor',
            field=models.ForeignKey(blank=True, help_text='Who will be energizing this kummitment? Is it for you or will you offer it to someone else?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kummitments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='measurable',
            field=models.BooleanField(default=False, help_text='Are both the task (evidence of done) and the kummitment (success actions) measurable/quantifiable as the completion status moves from 0% to 100%? Is there a clear difference between success and non-success for both the task and kummitment? In other words, is there an objective (rather than subjective) measure of success and means of checking?'),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='needhelp',
            field=models.BooleanField(default=False, verbose_name='Do you need help?'),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='reflection',
            field=models.TextField(blank=True, help_text='When you have reached a status of 99% or 100% complete, take a few moments to reflect on how this went and what you might have done better. Be sure to give yourself some love for what you did right and for the effort you put in!', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='relevant',
            field=models.BooleanField(default=False, help_text='Will doing this lead to the desired result? Is this task central to the goals of the organization, project, circle, role, or Member? Does successful completion make a difference in our world? Is it clearly explained how? Does the kummitor have the appropriate knowledge, skill, experience, and wisdom to make this happen in the face of challenges?'),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='specific',
            field=models.BooleanField(default=False, help_text='Are both the kummitment and the related task written in a simple manner clearly defining what the kummitor will do? Does it use clear, direct language about what will be done and how this will move the project, role, circle, or Member forward?'),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='start',
            field=models.DateTimeField(blank=True, help_text='When can you start this? Is it now, or are you waiting on another deliverable or some other dependency?', null=True),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='status',
            field=models.CharField(blank=True, help_text="What do you estimate is the percent completion of this kummitment? If you're just starting, it's 0%. As you perform work cycles, estimate your percent completion so the rest of the team knows what's going on. The default maximum is 99%. Once a qualified Member, partner, or client has asserted that you have completed the task it will move to 100%. This is an important part of creating trust in your data-backed professional profile.", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='task',
            field=models.ForeignKey(help_text='Which task is this kummitment for?', on_delete=django.db.models.deletion.PROTECT, to='managetime.Task'),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='timebound',
            field=models.BooleanField(default=False, help_text='Is it clear when this will be started, energized, and completed? Does the completion date create a practical sense of urgency? Goals should be linked to a timeframe that gives you a practical sense of urgency, or results in tenshion between the current reality and the vision of the goal so as to help drive the kummitor forward. Without such tension, the task is unlikely to drive relevant outcomes (especially in handling the ambiguous sitations that result in higher pay).'),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='wealthy',
            field=models.TextField(blank=True, help_text='(Optional) How will energizing this kummitment make you wealthier?', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='wise',
            field=models.TextField(blank=True, help_text='(Optional) How will energizing this commitment make you more wise?', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='circle',
            field=models.ForeignKey(blank=True, help_text='If this task is for a circle, which circle?', null=True, on_delete=django.db.models.deletion.PROTECT, to='managetime.Circle'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Explain what will need to happen in order for this task to be accomplished', max_length=600, verbose_name='Task description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='If this task is for a project, which project?', null=True, on_delete=django.db.models.deletion.PROTECT, to='managetime.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.ForeignKey(blank=True, help_text='If this task is for a role, which role?', null=True, on_delete=django.db.models.deletion.PROTECT, to='managetime.Role'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(help_text='Write a short name describing the task', max_length=30, verbose_name='Task name'),
        ),
    ]
