# Generated by Django 2.0.5 on 2018-06-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0023_auto_20180624_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='monthlyreport',
            field=models.TextField(blank=True, db_column='monthlyreport', max_length=600, null=True),
        ),
        migrations.RenameField('role','monthlyreport', 'monthly_report'),
        
        migrations.AlterField(
            model_name='task',
            name='doneevidence',
            field=models.TextField(blank=True, db_column='doneevidence', help_text='What deliverables, links, assertions (by clients, partners, or Members), or other evidence are required to show completion of this task?', max_length=600, null=True, verbose_name='Evidence of done'),
        ),
        migrations.RenameField('task','doneevidence', 'done_evidence'),
        
        # migrations.AlterField(
        #     model_name='project',
        #     name='gigvaluedetails',
        #     field=models.CharField(db_column='gigvaluedetails', max_length=600),
        # ),
        # migrations.RenameField('project','gigvaluedetails', 'gig_value_details'),
     
        # migrations.AlterField(
        #     model_name='project',
        #     name='relatedroles',
        #     field=models.ForeignKey(db_column='relatedroles', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='managetime.Role'),  
        # ),
        # migrations.RenameField('project','relatedroles', 'related_roles'),
        
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.TextField(max_length=60, null=True),
        ),
    ]
