# Generated by Django 2.0.5 on 2018-06-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0024_auto_20180624_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectlead',
        ),
        migrations.AddField(
            model_name='project',
            name='expected_duration',
            field=models.TextField(db_column='expectedduration', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='gig_value_details',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='related_roles',
            field=models.ForeignKey(db_column='relatedroles', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='managetime.Role'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_owner', to='managetime.Client'),
        ),
    ]
